SUPABASE_RESOURCE_PROVIDER = "supabase"
SUPABASE_OAUTH_PROVIDER = "supabase_mgmt"
SUPABASE_RESOURCE_TYPE_PROJECT = "project"

POSTGRES_RESOURCE_PROVIDER = "postgres"
POSTGRES_RESOURCE_TYPE_DATABASE = "database"

MCP_RESOURCE_PROVIDER = "mcp"
MCP_RESOURCE_TYPE_SERVER = "mcp_server"
