"""initial_sqlmodel_schema

Revision ID: 93f7d22238b9
Revises:
Create Date: 2026-01-06 17:19:14.623316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = '93f7d22238b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'RELEASED', 'ARCHIVED', name='workflowversionstatus'), nullable=False),
    sa.Column('spec', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_from_draft_revision', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('spec_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'version_number', name='uq_workflow_version')
    )
    op.create_index(op.f('ix_workflow_versions_workflow_id'), 'workflow_versions', ['workflow_id'], unique=False)
    op.create_table('workflow_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('spec', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation_warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_drafts_workflow_id'), 'workflow_drafts', ['workflow_id'], unique=True)
    op.drop_table('block_executions')
    op.drop_index(op.f('checkpoint_blobs_thread_id_idx'), table_name='checkpoint_blobs')
    op.drop_table('checkpoint_blobs')
    op.drop_index(op.f('checkpoints_thread_id_idx'), table_name='checkpoints')
    op.drop_table('checkpoints')
    op.drop_table('workflow_blocks')
    op.drop_index(op.f('checkpoint_writes_thread_id_idx'), table_name='checkpoint_writes')
    op.drop_table('checkpoint_writes')
    op.drop_table('workflow_executions')
    op.drop_table('workflow_edges')
    op.drop_table('checkpoint_migrations')
    op.drop_table('aerich')
    op.alter_column('integration_resources', 'oauth_connection_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('integration_resources', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('integration_resources', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('integration_resources', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index(op.f('idx_integration_user_id_5ce07e'), table_name='integration_resources')
    op.drop_constraint(op.f('uid_integration_oauth_c_f67a73'), 'integration_resources', type_='unique')
    op.create_index(op.f('ix_integration_resources_user_id'), 'integration_resources', ['user_id'], unique=False)
    op.create_index('ix_integration_resources_user_provider_type', 'integration_resources', ['user_id', 'provider', 'resource_type'], unique=False)
    op.create_unique_constraint('uq_resource_connection_type_id', 'integration_resources', ['oauth_connection_id', 'resource_type', 'resource_id'])
    op.drop_constraint(op.f('integration_resources_user_id_fkey'), 'integration_resources', type_='foreignkey')
    op.drop_constraint(op.f('integration_resources_oauth_connection_id_fkey'), 'integration_resources', type_='foreignkey')
    op.create_foreign_key(None, 'integration_resources', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'integration_resources', 'oauth_connections', ['oauth_connection_id'], ['id'])
    op.drop_table_comment(
        'integration_resources',
        existing_comment='Persisted resource binding that hangs off an OAuth connection.',
        schema=None
    )
    op.alter_column('integration_secrets', 'oauth_connection_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('integration_secrets', 'resource_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('integration_secrets', 'value_enc',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('integration_secrets', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('integration_secrets', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('integration_secrets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('integration_secrets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index(op.f('idx_integration_user_id_edae4e'), table_name='integration_secrets')
    op.drop_constraint(op.f('uid_integration_oauth_c_965e89'), 'integration_secrets', type_='unique')
    op.drop_constraint(op.f('uid_integration_resourc_953d72'), 'integration_secrets', type_='unique')
    op.create_index('ix_integration_secrets_user_provider_type', 'integration_secrets', ['user_id', 'provider', 'secret_type'], unique=False)
    op.create_unique_constraint('uq_secret_connection_name', 'integration_secrets', ['oauth_connection_id', 'name'])
    op.create_unique_constraint('uq_secret_resource_name', 'integration_secrets', ['resource_id', 'name'])
    op.drop_constraint(op.f('integration_secrets_oauth_connection_id_fkey'), 'integration_secrets', type_='foreignkey')
    op.drop_constraint(op.f('integration_secrets_resource_id_fkey'), 'integration_secrets', type_='foreignkey')
    op.drop_constraint(op.f('integration_secrets_user_id_fkey'), 'integration_secrets', type_='foreignkey')
    op.create_foreign_key(None, 'integration_secrets', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'integration_secrets', 'oauth_connections', ['oauth_connection_id'], ['id'])
    op.create_foreign_key(None, 'integration_secrets', 'integration_resources', ['resource_id'], ['id'])
    op.drop_table_comment(
        'integration_secrets',
        existing_comment='Generic vault for non-OAuth credentials tied to a connection or resource.',
        schema=None
    )
    op.alter_column('oauth_connections', 'access_token_enc',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('oauth_connections', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('oauth_connections', 'token_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('oauth_connections', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('oauth_connections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('oauth_connections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_constraint(op.f('uid_oauth_conne_user_id_edb955'), 'oauth_connections', type_='unique')
    op.create_unique_constraint('uq_oauth_user_provider_account', 'oauth_connections', ['user_id', 'provider', 'provider_account_id'])
    op.drop_constraint(op.f('oauth_connections_user_id_fkey'), 'oauth_connections', type_='foreignkey')
    op.create_foreign_key(None, 'oauth_connections', 'users', ['user_id'], ['id'])
    op.drop_table_comment(
        'oauth_connections',
        existing_comment='Database model for storing OAuth connections/tokens.',
        schema=None
    )
    op.add_column('projects', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('projects', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_foreign_key(None, 'projects', 'users', ['user_id'], ['id'])
    op.drop_table_comment(
        'projects',
        existing_comment='Database model for projects.',
        schema=None
    )
    op.alter_column('trigger_events', 'event_hash',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Deterministic hash used when provider_event_id is unavailable.',
               existing_nullable=True)
    op.alter_column('trigger_events', 'occurred_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('trigger_events', 'received_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('trigger_events', 'event',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('trigger_events', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               type_=sa.Enum('RECEIVED', 'ROUTED', 'PROCESSED', 'FAILED', name='triggereventstatus'),
               comment=None,
               existing_comment='RECEIVED: received\nROUTED: routed\nPROCESSED: processed\nFAILED: failed',
               existing_nullable=False)
    op.drop_index(op.f('idx_trigger_eve_status_9e17ee'), table_name='trigger_events')
    op.drop_index(op.f('idx_trigger_eve_trigger_c2e9c3'), table_name='trigger_events')
    op.drop_constraint(op.f('uid_trigger_eve_trigger_b917c2'), 'trigger_events', type_='unique')
    op.drop_index(op.f('uid_trigger_eve_trigger_bfc70c'), table_name='trigger_events')
    op.create_index('ix_trigger_event_provider', 'trigger_events', ['trigger_key', 'provider_connection_id'], unique=False)
    op.create_index('ix_trigger_event_status', 'trigger_events', ['status', 'received_at'], unique=False)
    op.create_unique_constraint('uq_trigger_event_hash', 'trigger_events', ['trigger_key', 'provider_connection_id', 'event_hash'])
    op.create_unique_constraint('uq_trigger_event_provider_id', 'trigger_events', ['trigger_key', 'provider_connection_id', 'provider_event_id'])
    op.drop_table_comment(
        'trigger_events',
        existing_comment='Normalized incoming trigger event.',
        schema=None
    )
    op.alter_column('trigger_subscriptions', 'enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('trigger_subscriptions', 'poll_interval_seconds',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('trigger_subscriptions', 'next_poll_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='Next scheduled poll time (UTC).',
               existing_nullable=False)
    op.alter_column('trigger_subscriptions', 'poll_status',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
    op.alter_column('trigger_subscriptions', 'poll_backoff_seconds',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('trigger_subscriptions', 'poll_lock_expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('trigger_subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('trigger_subscriptions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index(op.f('idx_trigger_sub_trigger_d2ffa4'), table_name='trigger_subscriptions')
    op.drop_index(op.f('idx_trigger_sub_user_id_5c5218'), table_name='trigger_subscriptions')
    op.create_index('ix_trigger_sub_key_provider', 'trigger_subscriptions', ['trigger_key', 'provider_connection_id', 'enabled'], unique=False)
    op.create_index('ix_trigger_sub_user_workflow', 'trigger_subscriptions', ['user_id', 'workflow_id'], unique=False)
    op.create_index(op.f('ix_trigger_subscriptions_user_id'), 'trigger_subscriptions', ['user_id'], unique=False)
    op.create_index(op.f('ix_trigger_subscriptions_workflow_id'), 'trigger_subscriptions', ['workflow_id'], unique=False)
    op.drop_constraint(op.f('trigger_subscriptions_workflow_id_fkey'), 'trigger_subscriptions', type_='foreignkey')
    op.drop_constraint(op.f('trigger_subscriptions_user_id_fkey'), 'trigger_subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'trigger_subscriptions', 'workflows', ['workflow_id'], ['id'])
    op.create_foreign_key(None, 'trigger_subscriptions', 'users', ['user_id'], ['id'])
    op.drop_table_comment(
        'trigger_subscriptions',
        existing_comment='Trigger configuration attached to a workflow.',
        schema=None
    )
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index(op.f('idx_users_user_id_a795d9'), table_name='users')
    op.drop_constraint(op.f('users_user_id_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.drop_table_comment(
        'users',
        existing_comment='Database model for authenticated users.',
        schema=None
    )
    op.alter_column('workflow_chat_messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('workflow_chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_workflow_chat_messages_created_at'), 'workflow_chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_workflow_chat_messages_session_id'), 'workflow_chat_messages', ['session_id'], unique=False)
    op.drop_constraint(op.f('fk_workflow_workflow_9fa660a4'), 'workflow_chat_messages', type_='foreignkey')
    op.drop_constraint(op.f('workflow_chat_messages_session_id_fkey'), 'workflow_chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'workflow_chat_messages', 'workflow_chat_sessions', ['session_id'], ['id'])
    op.create_foreign_key(None, 'workflow_chat_messages', 'workflow_proposals', ['proposal_id'], ['id'])
    op.drop_table_comment(
        'workflow_chat_messages',
        existing_comment='Individual message in a chat session.',
        schema=None
    )
    op.alter_column('workflow_chat_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('workflow_chat_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index(op.f('idx_workflow_ch_thread__42ac7b'), table_name='workflow_chat_sessions')
    op.drop_constraint(op.f('workflow_chat_sessions_thread_id_key'), 'workflow_chat_sessions', type_='unique')
    op.create_index(op.f('ix_workflow_chat_sessions_thread_id'), 'workflow_chat_sessions', ['thread_id'], unique=True)
    op.create_index(op.f('ix_workflow_chat_sessions_updated_at'), 'workflow_chat_sessions', ['updated_at'], unique=False)
    op.create_index(op.f('ix_workflow_chat_sessions_user_id'), 'workflow_chat_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_workflow_chat_sessions_workflow_id'), 'workflow_chat_sessions', ['workflow_id'], unique=False)
    op.drop_constraint(op.f('workflow_chat_sessions_workflow_id_fkey'), 'workflow_chat_sessions', type_='foreignkey')
    op.drop_constraint(op.f('workflow_chat_sessions_user_id_fkey'), 'workflow_chat_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'workflow_chat_sessions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'workflow_chat_sessions', 'workflows', ['workflow_id'], ['id'])
    op.drop_table_comment(
        'workflow_chat_sessions',
        existing_comment='Chat session for workflow assistant.',
        schema=None
    )
    op.alter_column('workflow_proposals', 'spec',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('workflow_proposals', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('workflow_proposals', 'decided_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('workflow_proposals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('workflow_proposals', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_workflow_proposals_created_at'), 'workflow_proposals', ['created_at'], unique=False)
    op.create_index(op.f('ix_workflow_proposals_created_by_id'), 'workflow_proposals', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_workflow_proposals_session_id'), 'workflow_proposals', ['session_id'], unique=False)
    op.create_index(op.f('ix_workflow_proposals_workflow_id'), 'workflow_proposals', ['workflow_id'], unique=False)
    op.drop_constraint(op.f('workflow_proposals_created_by_id_fkey'), 'workflow_proposals', type_='foreignkey')
    op.drop_constraint(op.f('workflow_proposals_session_id_fkey'), 'workflow_proposals', type_='foreignkey')
    op.drop_constraint(op.f('workflow_proposals_workflow_id_fkey'), 'workflow_proposals', type_='foreignkey')
    op.create_foreign_key(None, 'workflow_proposals', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key(None, 'workflow_proposals', 'workflow_chat_sessions', ['session_id'], ['id'])
    op.create_foreign_key(None, 'workflow_proposals', 'workflows', ['workflow_id'], ['id'])
    op.drop_table_comment(
        'workflow_proposals',
        existing_comment='Reviewable workflow edit proposal.',
        schema=None
    )
    op.alter_column('workflow_records', 'spec',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('workflow_records', 'version',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('workflow_records', 'last_compile_ok',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('workflow_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('workflow_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_workflow_records_updated_at'), 'workflow_records', ['updated_at'], unique=False)
    op.create_index(op.f('ix_workflow_records_user_id'), 'workflow_records', ['user_id'], unique=False)
    op.drop_constraint(op.f('workflow_records_user_id_fkey'), 'workflow_records', type_='foreignkey')
    op.create_foreign_key(None, 'workflow_records', 'users', ['user_id'], ['id'])
    op.drop_table_comment(
        'workflow_records',
        existing_comment='Normalized workflow entity backed by WorkflowSpec JSON.',
        schema=None
    )
    op.add_column('workflow_runs', sa.Column('workflow_version_id', sa.Integer(), nullable=True))
    op.add_column('workflow_runs', sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.alter_column('workflow_runs', 'spec',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('workflow_runs', 'source',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               type_=sa.Enum('MANUAL', 'TRIGGER', name='workflowrunsource'),
               comment=None,
               existing_comment='MANUAL: manual\nTRIGGER: trigger',
               existing_nullable=False)
    op.alter_column('workflow_runs', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               type_=sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', name='workflowrunstatus'),
               comment=None,
               existing_comment='QUEUED: queued\nRUNNING: running\nSUCCEEDED: succeeded\nFAILED: failed\nCANCELLED: cancelled',
               existing_nullable=False)
    op.alter_column('workflow_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('workflow_runs', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('workflow_runs', 'finished_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_workflow_runs_created_at'), 'workflow_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_workflow_runs_user_id'), 'workflow_runs', ['user_id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_workflow_id'), 'workflow_runs', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_workflow_version_id'), 'workflow_runs', ['workflow_version_id'], unique=False)
    op.drop_constraint(op.f('workflow_runs_user_id_fkey'), 'workflow_runs', type_='foreignkey')
    op.drop_constraint(op.f('workflow_runs_workflow_id_fkey'), 'workflow_runs', type_='foreignkey')
    op.drop_constraint(op.f('workflow_runs_subscription_id_fkey'), 'workflow_runs', type_='foreignkey')
    op.drop_constraint(op.f('workflow_runs_trigger_event_id_fkey'), 'workflow_runs', type_='foreignkey')
    op.create_foreign_key(None, 'workflow_runs', 'workflow_versions', ['workflow_version_id'], ['id'])
    op.create_foreign_key(None, 'workflow_runs', 'trigger_events', ['trigger_event_id'], ['id'])
    op.create_foreign_key(None, 'workflow_runs', 'trigger_subscriptions', ['subscription_id'], ['id'])
    op.create_foreign_key(None, 'workflow_runs', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'workflow_runs', 'workflows', ['workflow_id'], ['id'])
    op.drop_table_comment(
        'workflow_runs',
        existing_comment='Persisted workflow run metadata (no telemetry).',
        schema=None
    )
    op.drop_column('workflow_runs', 'workflow_version')
    op.add_column('workflows', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('workflows', sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('workflows', sa.Column('published_version_id', sa.Integer(), nullable=True))
    op.alter_column('workflows', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('workflows', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_workflows_updated_at'), 'workflows', ['updated_at'], unique=False)
    op.create_index(op.f('ix_workflows_user_id'), 'workflows', ['user_id'], unique=False)
    op.drop_constraint(op.f('workflows_user_id_fkey'), 'workflows', type_='foreignkey')
    op.create_foreign_key(None, 'workflows', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'workflows', 'workflow_versions', ['published_version_id'], ['id'])
    op.drop_table_comment(
        'workflows',
        existing_comment='Main workflow entity.',
        schema=None
    )
    op.drop_column('workflows', 'is_active')
    op.drop_column('workflows', 'schema_version')
    op.drop_column('workflows', 'graph_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('graph_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('workflows', sa.Column('schema_version', sa.VARCHAR(length=50), server_default=sa.text("'1.0'::character varying"), autoincrement=False, nullable=False))
    op.add_column('workflows', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.create_table_comment(
        'workflows',
        'Main workflow entity.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'workflows', type_='foreignkey')
    op.drop_constraint(None, 'workflows', type_='foreignkey')
    op.create_foreign_key(op.f('workflows_user_id_fkey'), 'workflows', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_workflows_user_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_updated_at'), table_name='workflows')
    op.alter_column('workflows', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('workflows', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_column('workflows', 'published_version_id')
    op.drop_column('workflows', 'meta')
    op.drop_column('workflows', 'tags')
    op.add_column('workflow_runs', sa.Column('workflow_version', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_table_comment(
        'workflow_runs',
        'Persisted workflow run metadata (no telemetry).',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'workflow_runs', type_='foreignkey')
    op.drop_constraint(None, 'workflow_runs', type_='foreignkey')
    op.drop_constraint(None, 'workflow_runs', type_='foreignkey')
    op.drop_constraint(None, 'workflow_runs', type_='foreignkey')
    op.drop_constraint(None, 'workflow_runs', type_='foreignkey')
    op.create_foreign_key(op.f('workflow_runs_trigger_event_id_fkey'), 'workflow_runs', 'trigger_events', ['trigger_event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('workflow_runs_subscription_id_fkey'), 'workflow_runs', 'trigger_subscriptions', ['subscription_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('workflow_runs_workflow_id_fkey'), 'workflow_runs', 'workflow_records', ['workflow_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('workflow_runs_user_id_fkey'), 'workflow_runs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_workflow_runs_workflow_version_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_workflow_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_user_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_created_at'), table_name='workflow_runs')
    op.alter_column('workflow_runs', 'finished_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('workflow_runs', 'started_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('workflow_runs', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('workflow_runs', 'status',
               existing_type=sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', name='workflowrunstatus'),
               server_default=sa.text("'queued'::character varying"),
               type_=sa.VARCHAR(length=20),
               comment='QUEUED: queued\nRUNNING: running\nSUCCEEDED: succeeded\nFAILED: failed\nCANCELLED: cancelled',
               existing_nullable=False)
    op.alter_column('workflow_runs', 'source',
               existing_type=sa.Enum('MANUAL', 'TRIGGER', name='workflowrunsource'),
               server_default=sa.text("'manual'::character varying"),
               type_=sa.VARCHAR(length=20),
               comment='MANUAL: manual\nTRIGGER: trigger',
               existing_nullable=False)
    op.alter_column('workflow_runs', 'spec',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('workflow_runs', 'thread_id')
    op.drop_column('workflow_runs', 'workflow_version_id')
    op.create_table_comment(
        'workflow_records',
        'Normalized workflow entity backed by WorkflowSpec JSON.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'workflow_records', type_='foreignkey')
    op.create_foreign_key(op.f('workflow_records_user_id_fkey'), 'workflow_records', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_workflow_records_user_id'), table_name='workflow_records')
    op.drop_index(op.f('ix_workflow_records_updated_at'), table_name='workflow_records')
    op.alter_column('workflow_records', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('workflow_records', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('workflow_records', 'last_compile_ok',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('workflow_records', 'version',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('workflow_records', 'spec',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.create_table_comment(
        'workflow_proposals',
        'Reviewable workflow edit proposal.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'workflow_proposals', type_='foreignkey')
    op.drop_constraint(None, 'workflow_proposals', type_='foreignkey')
    op.drop_constraint(None, 'workflow_proposals', type_='foreignkey')
    op.create_foreign_key(op.f('workflow_proposals_workflow_id_fkey'), 'workflow_proposals', 'workflow_records', ['workflow_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('workflow_proposals_session_id_fkey'), 'workflow_proposals', 'workflow_chat_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('workflow_proposals_created_by_id_fkey'), 'workflow_proposals', 'users', ['created_by_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_workflow_proposals_workflow_id'), table_name='workflow_proposals')
    op.drop_index(op.f('ix_workflow_proposals_session_id'), table_name='workflow_proposals')
    op.drop_index(op.f('ix_workflow_proposals_created_by_id'), table_name='workflow_proposals')
    op.drop_index(op.f('ix_workflow_proposals_created_at'), table_name='workflow_proposals')
    op.alter_column('workflow_proposals', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('workflow_proposals', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('workflow_proposals', 'decided_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('workflow_proposals', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.alter_column('workflow_proposals', 'spec',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.create_table_comment(
        'workflow_chat_sessions',
        'Chat session for workflow assistant.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'workflow_chat_sessions', type_='foreignkey')
    op.drop_constraint(None, 'workflow_chat_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('workflow_chat_sessions_user_id_fkey'), 'workflow_chat_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('workflow_chat_sessions_workflow_id_fkey'), 'workflow_chat_sessions', 'workflow_records', ['workflow_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_workflow_chat_sessions_workflow_id'), table_name='workflow_chat_sessions')
    op.drop_index(op.f('ix_workflow_chat_sessions_user_id'), table_name='workflow_chat_sessions')
    op.drop_index(op.f('ix_workflow_chat_sessions_updated_at'), table_name='workflow_chat_sessions')
    op.drop_index(op.f('ix_workflow_chat_sessions_thread_id'), table_name='workflow_chat_sessions')
    op.create_unique_constraint(op.f('workflow_chat_sessions_thread_id_key'), 'workflow_chat_sessions', ['thread_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_workflow_ch_thread__42ac7b'), 'workflow_chat_sessions', ['thread_id'], unique=False)
    op.alter_column('workflow_chat_sessions', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('workflow_chat_sessions', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.create_table_comment(
        'workflow_chat_messages',
        'Individual message in a chat session.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'workflow_chat_messages', type_='foreignkey')
    op.drop_constraint(None, 'workflow_chat_messages', type_='foreignkey')
    op.create_foreign_key(op.f('workflow_chat_messages_session_id_fkey'), 'workflow_chat_messages', 'workflow_chat_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_workflow_workflow_9fa660a4'), 'workflow_chat_messages', 'workflow_proposals', ['proposal_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_workflow_chat_messages_session_id'), table_name='workflow_chat_messages')
    op.drop_index(op.f('ix_workflow_chat_messages_created_at'), table_name='workflow_chat_messages')
    op.alter_column('workflow_chat_messages', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('workflow_chat_messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_table_comment(
        'users',
        'Database model for authenticated users.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.create_unique_constraint(op.f('users_user_id_key'), 'users', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_user_id_a795d9'), 'users', ['user_id'], unique=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.create_table_comment(
        'trigger_subscriptions',
        'Trigger configuration attached to a workflow.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'trigger_subscriptions', type_='foreignkey')
    op.drop_constraint(None, 'trigger_subscriptions', type_='foreignkey')
    op.create_foreign_key(op.f('trigger_subscriptions_user_id_fkey'), 'trigger_subscriptions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('trigger_subscriptions_workflow_id_fkey'), 'trigger_subscriptions', 'workflow_records', ['workflow_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_trigger_subscriptions_workflow_id'), table_name='trigger_subscriptions')
    op.drop_index(op.f('ix_trigger_subscriptions_user_id'), table_name='trigger_subscriptions')
    op.drop_index('ix_trigger_sub_user_workflow', table_name='trigger_subscriptions')
    op.drop_index('ix_trigger_sub_key_provider', table_name='trigger_subscriptions')
    op.create_index(op.f('idx_trigger_sub_user_id_5c5218'), 'trigger_subscriptions', ['user_id', 'workflow_id'], unique=False)
    op.create_index(op.f('idx_trigger_sub_trigger_d2ffa4'), 'trigger_subscriptions', ['trigger_key', 'provider_connection_id', 'enabled'], unique=False)
    op.alter_column('trigger_subscriptions', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('trigger_subscriptions', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('trigger_subscriptions', 'poll_lock_expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('trigger_subscriptions', 'poll_backoff_seconds',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('trigger_subscriptions', 'poll_status',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'ok'::character varying"),
               existing_nullable=False)
    op.alter_column('trigger_subscriptions', 'next_poll_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               comment='Next scheduled poll time (UTC).',
               existing_nullable=False)
    op.alter_column('trigger_subscriptions', 'poll_interval_seconds',
               existing_type=sa.INTEGER(),
               server_default=sa.text('60'),
               existing_nullable=False)
    op.alter_column('trigger_subscriptions', 'enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.create_table_comment(
        'trigger_events',
        'Normalized incoming trigger event.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint('uq_trigger_event_provider_id', 'trigger_events', type_='unique')
    op.drop_constraint('uq_trigger_event_hash', 'trigger_events', type_='unique')
    op.drop_index('ix_trigger_event_status', table_name='trigger_events')
    op.drop_index('ix_trigger_event_provider', table_name='trigger_events')
    op.create_index(op.f('uid_trigger_eve_trigger_bfc70c'), 'trigger_events', ['trigger_key', 'provider_connection_id', 'event_hash'], unique=True)
    op.create_unique_constraint(op.f('uid_trigger_eve_trigger_b917c2'), 'trigger_events', ['trigger_key', 'provider_connection_id', 'provider_event_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_trigger_eve_trigger_c2e9c3'), 'trigger_events', ['trigger_key', 'provider_connection_id'], unique=False)
    op.create_index(op.f('idx_trigger_eve_status_9e17ee'), 'trigger_events', ['status', 'received_at'], unique=False)
    op.alter_column('trigger_events', 'status',
               existing_type=sa.Enum('RECEIVED', 'ROUTED', 'PROCESSED', 'FAILED', name='triggereventstatus'),
               server_default=sa.text("'received'::character varying"),
               type_=sa.VARCHAR(length=20),
               comment='RECEIVED: received\nROUTED: routed\nPROCESSED: processed\nFAILED: failed',
               existing_nullable=False)
    op.alter_column('trigger_events', 'event',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('trigger_events', 'received_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('trigger_events', 'occurred_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('trigger_events', 'event_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='Deterministic hash used when provider_event_id is unavailable.',
               existing_nullable=True)
    op.create_table_comment(
        'projects',
        'Database model for projects.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.alter_column('projects', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('projects', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('projects', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_column('projects', 'user_id')
    op.create_table_comment(
        'oauth_connections',
        'Database model for storing OAuth connections/tokens.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'oauth_connections', type_='foreignkey')
    op.create_foreign_key(op.f('oauth_connections_user_id_fkey'), 'oauth_connections', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_oauth_user_provider_account', 'oauth_connections', type_='unique')
    op.create_unique_constraint(op.f('uid_oauth_conne_user_id_edb955'), 'oauth_connections', ['user_id', 'provider', 'provider_account_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('oauth_connections', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('oauth_connections', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('oauth_connections', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'active'::character varying"),
               existing_nullable=False)
    op.alter_column('oauth_connections', 'token_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'Bearer'::character varying"),
               existing_nullable=False)
    op.alter_column('oauth_connections', 'expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('oauth_connections', 'access_token_enc',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_table_comment(
        'integration_secrets',
        'Generic vault for non-OAuth credentials tied to a connection or resource.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'integration_secrets', type_='foreignkey')
    op.drop_constraint(None, 'integration_secrets', type_='foreignkey')
    op.drop_constraint(None, 'integration_secrets', type_='foreignkey')
    op.create_foreign_key(op.f('integration_secrets_user_id_fkey'), 'integration_secrets', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('integration_secrets_resource_id_fkey'), 'integration_secrets', 'integration_resources', ['resource_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('integration_secrets_oauth_connection_id_fkey'), 'integration_secrets', 'oauth_connections', ['oauth_connection_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_secret_resource_name', 'integration_secrets', type_='unique')
    op.drop_constraint('uq_secret_connection_name', 'integration_secrets', type_='unique')
    op.drop_index('ix_integration_secrets_user_provider_type', table_name='integration_secrets')
    op.create_unique_constraint(op.f('uid_integration_resourc_953d72'), 'integration_secrets', ['resource_id', 'name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uid_integration_oauth_c_965e89'), 'integration_secrets', ['oauth_connection_id', 'name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_integration_user_id_edae4e'), 'integration_secrets', ['user_id', 'provider', 'secret_type'], unique=False)
    op.alter_column('integration_secrets', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('integration_secrets', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('integration_secrets', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'active'::character varying"),
               existing_nullable=False)
    op.alter_column('integration_secrets', 'expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('integration_secrets', 'value_enc',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('integration_secrets', 'resource_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('integration_secrets', 'oauth_connection_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.create_table_comment(
        'integration_resources',
        'Persisted resource binding that hangs off an OAuth connection.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'integration_resources', type_='foreignkey')
    op.drop_constraint(None, 'integration_resources', type_='foreignkey')
    op.create_foreign_key(op.f('integration_resources_oauth_connection_id_fkey'), 'integration_resources', 'oauth_connections', ['oauth_connection_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('integration_resources_user_id_fkey'), 'integration_resources', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_resource_connection_type_id', 'integration_resources', type_='unique')
    op.drop_index('ix_integration_resources_user_provider_type', table_name='integration_resources')
    op.drop_index(op.f('ix_integration_resources_user_id'), table_name='integration_resources')
    op.create_unique_constraint(op.f('uid_integration_oauth_c_f67a73'), 'integration_resources', ['oauth_connection_id', 'resource_type', 'resource_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_integration_user_id_5ce07e'), 'integration_resources', ['user_id', 'provider', 'resource_type'], unique=False)
    op.alter_column('integration_resources', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('integration_resources', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('integration_resources', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'active'::character varying"),
               existing_nullable=False)
    op.alter_column('integration_resources', 'oauth_connection_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.create_table('aerich',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('version', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('app', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('aerich_pkey'))
    )
    op.create_table('checkpoint_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('checkpoint_migrations_pkey'))
    )
    op.create_table('workflow_edges',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('source_handle', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('target_handle', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('source_block_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_block_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('workflow_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['source_block_id'], ['workflow_blocks.id'], name=op.f('workflow_edges_source_block_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_block_id'], ['workflow_blocks.id'], name=op.f('workflow_edges_target_block_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('workflow_edges_workflow_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('workflow_edges_pkey')),
    comment='Connections between blocks.'
    )
    op.create_table('workflow_executions',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('workflow_executions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('workflow_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='workflow_executions_user_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name='workflow_executions_workflow_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='workflow_executions_pkey'),
    comment='Workflow execution history.',
    postgresql_ignore_search_path=False
    )
    op.create_table('checkpoint_writes',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('task_path', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx', name=op.f('checkpoint_writes_pkey'))
    )
    op.create_index(op.f('checkpoint_writes_thread_id_idx'), 'checkpoint_writes', ['thread_id'], unique=False)
    op.create_table('workflow_blocks',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('workflow_blocks_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('block_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('block_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('block_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('position_x', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('position_y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('oauth_scope', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('workflow_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name='workflow_blocks_workflow_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='workflow_blocks_pkey'),
    sa.UniqueConstraint('workflow_id', 'block_id', name='uid_workflow_bl_workflo_650105', postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='Individual blocks (nodes) in workflow.',
    postgresql_ignore_search_path=False
    )
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parent_checkpoint_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', name=op.f('checkpoints_pkey'))
    )
    op.create_index(op.f('checkpoints_thread_id_idx'), 'checkpoints', ['thread_id'], unique=False)
    op.create_table('checkpoint_blobs',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'channel', 'version', name=op.f('checkpoint_blobs_pkey'))
    )
    op.create_index(op.f('checkpoint_blobs_thread_id_idx'), 'checkpoint_blobs', ['thread_id'], unique=False)
    op.create_table('block_executions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('execution_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('block_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('execution_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['workflow_blocks.id'], name=op.f('block_executions_block_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_executions.id'], name=op.f('block_executions_execution_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('block_executions_pkey')),
    comment='Per-block execution logs.'
    )
    op.drop_index(op.f('ix_workflow_drafts_workflow_id'), table_name='workflow_drafts')
    op.drop_table('workflow_drafts')
    op.drop_index(op.f('ix_workflow_versions_workflow_id'), table_name='workflow_versions')
    op.drop_table('workflow_versions')
    # ### end Alembic commands ###
