"""
Database Models for Seer - Tortoise ORM

This module defines all database models using Tortoise ORM.
Replaces raw SQL queries with ORM-based operations.
"""

from tortoise import fields
from tortoise.models import Model
from datetime import datetime
from typing import Optional
from pathlib import Path


class Thread(Model):
    """Conversation thread model"""
    
    # id field is auto-generated by Tortoise ORM
    thread_id = fields.CharField(max_length=255, unique=True, index=True)
    created_at = fields.DatetimeField(auto_now_add=True)
    updated_at = fields.DatetimeField(auto_now=True)
    user_id = fields.CharField(max_length=255, null=True)
    status = fields.CharField(max_length=50, default='active')
    metadata = fields.JSONField(null=True)
    
    # Agent configuration fields (stored by customer success agent on first message)
    github_url = fields.CharField(max_length=500, null=True)
    agent_host = fields.CharField(max_length=255, null=True)
    agent_port = fields.IntField(null=True)
    agent_id = fields.CharField(max_length=255, null=True)
    
    class Meta:
        table = "threads"
        ordering = ["-updated_at"]
    
    def __str__(self):
        return f"Thread({self.thread_id})"


class Message(Model):
    """Message model for storing chat messages"""
    
    # id field is auto-generated by Tortoise ORM
    thread = fields.ForeignKeyField(
        'models.Thread', 
        related_name='messages',
        on_delete=fields.CASCADE,
        to_field='thread_id',
        db_constraint=False
    )
    message_id = fields.CharField(max_length=255, unique=True, index=True)
    timestamp = fields.DatetimeField(index=True)
    role = fields.CharField(max_length=50)
    sender = fields.CharField(max_length=255)
    content = fields.TextField()
    message_type = fields.CharField(max_length=50, null=True)
    metadata = fields.JSONField(null=True)
    
    class Meta:
        table = "messages"
        ordering = ["timestamp"]
    
    def __str__(self):
        return f"Message({self.message_id}, {self.sender})"


class Event(Model):
    """Event model for storing event bus events"""
    
    # id field is auto-generated by Tortoise ORM
    event_id = fields.CharField(max_length=255, unique=True, index=True)
    thread = fields.ForeignKeyField(
        'models.Thread',
        related_name='events',
        on_delete=fields.CASCADE,
        to_field='thread_id',
        null=True,
        db_constraint=False
    )
    timestamp = fields.DatetimeField(index=True)
    event_type = fields.CharField(max_length=100, index=True)
    sender = fields.CharField(max_length=255)
    payload = fields.JSONField()
    metadata = fields.JSONField(null=True)
    
    class Meta:
        table = "events"
        ordering = ["timestamp"]
    
    def __str__(self):
        return f"Event({self.event_id}, {self.event_type})"


class AgentActivity(Model):
    """Agent activity model for tracking agent actions"""
    
    # id field is auto-generated by Tortoise ORM
    thread = fields.ForeignKeyField(
        'models.Thread',
        related_name='activities',
        on_delete=fields.CASCADE,
        to_field='thread_id',
        db_constraint=False
    )
    agent_name = fields.CharField(max_length=255, index=True)
    timestamp = fields.DatetimeField(auto_now_add=True)
    activity_type = fields.CharField(max_length=100)
    description = fields.TextField(null=True)
    tool_name = fields.CharField(max_length=255, null=True)
    tool_input = fields.TextField(null=True)
    tool_output = fields.TextField(null=True)
    metadata = fields.JSONField(null=True)
    
    class Meta:
        table = "agent_activities"
        ordering = ["timestamp"]
    
    def __str__(self):
        return f"AgentActivity({self.agent_name}, {self.activity_type})"


class EvalSuite(Model):
    """Eval suite model for storing test suites"""
    
    # id field is auto-generated by Tortoise ORM
    suite_id = fields.CharField(max_length=255, unique=True, index=True)
    thread = fields.ForeignKeyField(
        'models.Thread',
        related_name='eval_suites',
        on_delete=fields.CASCADE,
        to_field='thread_id',
        null=True,
        db_constraint=False
    )
    spec_name = fields.CharField(max_length=255)
    spec_version = fields.CharField(max_length=50)
    target_agent_url = fields.CharField(max_length=500, null=True)
    target_agent_id = fields.CharField(max_length=255, null=True)
    test_cases = fields.JSONField()
    created_at = fields.DatetimeField(auto_now_add=True)
    metadata = fields.JSONField(null=True)
    
    class Meta:
        table = "eval_suites"
        ordering = ["-created_at"]
    
    def __str__(self):
        return f"EvalSuite({self.suite_id}, {self.spec_name})"


class TestResult(Model):
    """Test result model for storing eval results"""
    
    # id field is auto-generated by Tortoise ORM
    result_id = fields.CharField(max_length=255, unique=True, index=True)
    suite = fields.ForeignKeyField(
        'models.EvalSuite',
        related_name='test_results',
        on_delete=fields.CASCADE,
        to_field='suite_id',
        db_constraint=False
    )
    thread = fields.ForeignKeyField(
        'models.Thread',
        related_name='test_results',
        on_delete=fields.CASCADE,
        to_field='thread_id',
        db_constraint=False
    )
    test_case_id = fields.CharField(max_length=255)
    input_sent = fields.TextField()
    actual_output = fields.TextField()
    expected_behavior = fields.TextField()
    passed = fields.BooleanField()
    score = fields.FloatField()
    judge_reasoning = fields.TextField()
    created_at = fields.DatetimeField(auto_now_add=True)
    metadata = fields.JSONField(null=True)
    
    class Meta:
        table = "test_results"
        ordering = ["-created_at"]
    
    def __str__(self):
        return f"TestResult({self.result_id}, passed={self.passed})"


class Subscriber(Model):
    """Subscriber model for tracking event bus subscribers"""
    
    agent_name = fields.CharField(max_length=255, pk=True)
    registered_at = fields.DatetimeField(auto_now_add=True)
    last_poll = fields.DatetimeField(null=True)
    message_count = fields.IntField(default=0)
    publish_count = fields.IntField(default=0)
    filters = fields.JSONField(null=True)
    status = fields.CharField(max_length=50, default='active')
    metadata = fields.JSONField(null=True)
    
    class Meta:
        table = "subscribers"
    
    def __str__(self):
        return f"Subscriber({self.agent_name})"


# Tortoise ORM configuration for aerich migrations
TORTOISE_ORM_CONFIG = {
    "connections": {
        "default": f"sqlite://{Path(__file__).parent.parent / 'data' / 'seer.db'}"
    },
    "apps": {
        "models": {
            "models": ["shared.models", "aerich.models"],
            "default_connection": "default",
        }
    },
}

