"""
Middleware to sanitize tool_call_ids immediately after LLM generation.

This middleware intercepts model responses to strip leading/trailing
whitespace from tool_call_ids, preventing validation errors from
malformed IDs generated by OpenRouter/Kimi models.
"""
from typing import Any, Callable, Awaitable

from langchain.agents.middleware import AgentMiddleware

from seer.logger import get_logger
from seer.utilities.message_sanitizer import sanitize_tool_call_id

logger = get_logger(__name__)


class ToolCallSanitizationMiddleware(AgentMiddleware):
    """
    Middleware that sanitizes tool_call_ids in LLM responses.

    Intercepts model responses immediately after generation to strip
    leading/trailing whitespace from tool_call_ids.

    This prevents malformed IDs from OpenRouter/Kimi models (which may include
    leading spaces) from being stored in checkpoints or causing API validation
    errors.

    Example malformed IDs that get sanitized:
        - " list_available_tools:8" -> "list_available_tools:8"
        - " functions.search_tools:9" -> "functions.search_tools:9"
    """

    async def awrap_model_call(
        self,
        request: Any,
        handler: Callable[[Any], Awaitable[Any]],
    ) -> Any:
        """
        Intercept model response and sanitize tool_call_ids.

        Args:
            request: The model request (passed through)
            handler: The async handler to call the model

        Returns:
            The model response with sanitized tool_call_ids
        """
        response = await handler(request)

        # Sanitize tool_calls in the response
        if hasattr(response, 'tool_calls') and response.tool_calls:
            sanitized_count = 0
            for tc in response.tool_calls:
                if isinstance(tc, dict) and 'id' in tc:
                    original_id = tc['id']
                    sanitized_id = sanitize_tool_call_id(original_id)
                    if sanitized_id != original_id:
                        tc['id'] = sanitized_id
                        sanitized_count += 1
                        logger.debug(
                            "Sanitized tool_call_id: %s -> %s",
                            original_id, sanitized_id
                        )

            if sanitized_count > 0:
                logger.info(
                    "Sanitized %d malformed tool_call_id(s) in LLM response",
                    sanitized_count
                )

        return response
