"""
Middleware to sanitize tool_call_ids immediately after LLM generation.

This middleware intercepts model responses to strip leading/trailing
whitespace from tool_call_ids, preventing validation errors from
malformed IDs generated by OpenRouter/Kimi models.

Also retries on transient upstream provider errors (e.g. Venice/OpenRouter 500s).
"""
import asyncio
from typing import Any, Callable, Awaitable

from langchain.agents.middleware import AgentMiddleware

from seer.logger import get_logger
from seer.utilities.message_sanitizer import sanitize_tool_call_id

logger = get_logger(__name__)

_MAX_RETRIES = 3
_BACKOFF_SECONDS = [1, 2, 4]


def _is_transient_error(exc: Exception) -> bool:
    """Check if an openai.APIError is a transient upstream failure worth retrying."""
    # pylint: disable=import-outside-toplevel # Reason: openai may not be installed in all contexts
    try:
        from openai import APIError
    except ImportError:
        return False
    if not isinstance(exc, APIError):
        return False
    msg = str(exc).lower()
    # Retry on upstream provider errors (Venice, OpenRouter proxied 500s)
    if "upstream error" in msg:
        return True
    # Retry on generic 5xx status codes
    status = getattr(exc, "status_code", None) or getattr(exc, "http_status", None)
    if status is not None and status >= 500:
        return True
    return False


class ToolCallSanitizationMiddleware(AgentMiddleware):
    """
    Middleware that sanitizes tool_call_ids and retries transient LLM errors.

    1. Retries on transient upstream errors (500s, Venice/OpenRouter failures)
       with exponential backoff (1s, 2s, 4s).
    2. Strips leading/trailing whitespace from tool_call_ids to prevent
       validation errors from malformed IDs.
    """

    async def awrap_model_call(
        self,
        request: Any,
        handler: Callable[[Any], Awaitable[Any]],
    ) -> Any:
        """Intercept model call with retry + tool_call_id sanitization."""
        last_exc: Exception | None = None
        for attempt in range(_MAX_RETRIES):
            try:
                response = await handler(request)
                break
            except Exception as exc:  # pylint: disable=broad-exception-caught  # Reason: retry logic must catch all transient errors
                if not _is_transient_error(exc) or attempt == _MAX_RETRIES - 1:
                    raise
                last_exc = exc
                delay = _BACKOFF_SECONDS[attempt]
                logger.warning(
                    "Transient LLM error (attempt %d/%d), retrying in %ds: %s",
                    attempt + 1, _MAX_RETRIES, delay, exc,
                )
                await asyncio.sleep(delay)
        else:
            raise last_exc  # type: ignore[misc]  # unreachable but satisfies type checker

        # Sanitize tool_calls in the response
        if hasattr(response, 'tool_calls') and response.tool_calls:
            sanitized_count = 0
            for tc in response.tool_calls:
                if isinstance(tc, dict) and 'id' in tc:
                    original_id = tc['id']
                    sanitized_id = sanitize_tool_call_id(original_id)
                    if sanitized_id != original_id:
                        tc['id'] = sanitized_id
                        sanitized_count += 1
                        logger.debug(
                            "Sanitized tool_call_id: %s -> %s",
                            original_id, sanitized_id
                        )

            if sanitized_count > 0:
                logger.info(
                    "Sanitized %d malformed tool_call_id(s) in LLM response",
                    sanitized_count
                )

        return response
