import { useState } from "react";
import { HardDrive, FolderOpen } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { filesApi, type MimeTypeStats } from "@/lib/files-api";
import { fileKeys } from "@/lib/query-keys";
import { FilesManagementDialog } from "./FilesManagementDialog";

function CardHeaderContent({ isLoading }: { isLoading?: boolean }) {
  return (
    <CardHeader>
      <div className="flex items-center gap-3">
        <div className="w-10 h-10 rounded-lg bg-seer/10 flex items-center justify-center">
          <HardDrive className="h-5 w-5 text-seer" />
        </div>
        <div className="flex-1">
          <CardTitle className="text-base">File Storage</CardTitle>
          <CardDescription>
            {isLoading ? "Loading..." : "Manage your workflow files and uploads"}
          </CardDescription>
        </div>
      </div>
    </CardHeader>
  );
}

function StatItem({ label, value }: { label: string; value: string | number }) {
  return (
    <div className="flex items-center justify-between text-sm">
      <span className="text-muted-foreground">{label}</span>
      <span className="font-medium">{value}</span>
    </div>
  );
}

function TypeBreakdown({ stats }: { stats: MimeTypeStats[] }) {
  // Get top 3 types by file count
  const topTypes = [...stats]
    .sort((a, b) => b.file_count - a.file_count)
    .slice(0, 3);

  if (topTypes.length === 0) return null;

  const formatType = (mimeType: string): string => {
    if (mimeType.startsWith("image/")) return "Images";
    if (mimeType === "application/pdf") return "PDFs";
    if (mimeType.startsWith("text/")) return "Text files";
    if (mimeType === "application/json") return "JSON";
    if (mimeType.includes("document") || mimeType.includes("word")) return "Documents";
    if (mimeType.includes("spreadsheet") || mimeType.includes("excel")) return "Spreadsheets";
    return mimeType.split("/").pop() || "Other";
  };

  return (
    <div className="pt-2 border-t">
      <p className="text-xs text-muted-foreground mb-2">Top file types</p>
      <div className="flex flex-wrap gap-1.5">
        {topTypes.map((type) => (
          <span
            key={type.mime_type}
            className="inline-flex items-center rounded-full bg-muted px-2 py-0.5 text-[10px] font-medium text-muted-foreground"
          >
            {formatType(type.mime_type)} ({type.file_count})
          </span>
        ))}
      </div>
    </div>
  );
}

export function FilesCard() {
  const [dialogOpen, setDialogOpen] = useState(false);

  const { data: stats, isLoading } = useQuery({
    queryKey: fileKeys.stats(),
    queryFn: filesApi.getStorageStats,
  });

  if (isLoading) {
    return (
      <Card>
        <CardHeaderContent isLoading />
      </Card>
    );
  }

  const hasFiles = stats && stats.total_files > 0;

  return (
    <>
      <Card>
        <CardHeaderContent />
        <CardContent className="space-y-4">
          {!hasFiles ? (
            <div className="py-6 text-center">
              <FolderOpen className="h-10 w-10 text-muted-foreground/40 mx-auto mb-3" />
              <p className="text-sm text-muted-foreground">No files yet</p>
              <p className="text-xs text-muted-foreground mt-1">
                Files generated by workflows will appear here
              </p>
            </div>
          ) : (
            <div className="space-y-3">
              <StatItem label="Total files" value={stats.total_files} />
              <StatItem label="Storage used" value={stats.total_size_human} />
              <TypeBreakdown stats={stats.files_by_mime_type} />
            </div>
          )}

          <Button
            onClick={() => setDialogOpen(true)}
            className="w-full"
            variant="outline"
          >
            <HardDrive className="h-4 w-4 mr-2" />
            Manage Files
          </Button>
        </CardContent>
      </Card>

      <FilesManagementDialog open={dialogOpen} onOpenChange={setDialogOpen} />
    </>
  );
}
