"""
Tool Factory: Single source of truth for tool metadata across Nexus (LangGraph) and MCP (FastMCP).

Each tool has ONE implementation function used by both surfaces. ToolDefinition holds
(name, description, implementation) and generates framework-specific wrappers for both
LangGraph StructuredTool and FastMCP FunctionTool, preventing metadata drift.

Usage:
    from seer.tools.tool_factory import ToolDefinition, ToolSurface, unified_registry

    def register_my_tools():
        unified_registry.register(ToolDefinition(
            name="search_tools",
            description="Search for tools by intent",
            implementation=search_tools_impl,
        ))

    # LangGraph agent
    tools = unified_registry.get_langgraph_tools()

    # MCP server
    unified_registry.register_mcp_tools(mcp_server)
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Flag, auto
from typing import Any, Callable, Dict, List, Optional

from seer.logger import get_logger

logger = get_logger(__name__)


class ToolSurface(Flag):
    """Which surfaces a tool should be registered on."""
    NEXUS = auto()       # LangGraph agent
    MCP = auto()         # FastMCP server
    BOTH = NEXUS | MCP


@dataclass
class ToolDefinition:
    """
    Canonical definition of a tool shared across Nexus and MCP surfaces.

    Each tool has ONE implementation function (no decorators) used by both surfaces.
    Framework-specific wrappers are generated by to_langgraph_tool() and to_mcp_tool().

    Attributes:
        name: Canonical tool name
        description: Canonical docstring/description used by both surfaces
        implementation: The plain async function (no decorators)
        surface: Which surfaces to register on (default: BOTH)
        mcp_name: Override name on MCP (defaults to self.name)
        nexus_name: Override name on Nexus (defaults to self.name)
        mcp_tracking_name: PostHog tracking name (defaults to mcp_name or name)
    """
    name: str
    description: str
    implementation: Callable[..., Any]
    surface: ToolSurface = ToolSurface.BOTH
    mcp_name: Optional[str] = None
    nexus_name: Optional[str] = None
    mcp_tracking_name: Optional[str] = None

    def resolve_mcp_name(self) -> str:
        return self.mcp_name or self.name

    def _resolve_nexus_name(self) -> str:
        return self.nexus_name or self.name

    def _resolve_mcp_tracking_name(self) -> str:
        return self.mcp_tracking_name or self.resolve_mcp_name()

    def to_langgraph_tool(self) -> Any:
        """
        Convert to a LangChain StructuredTool for use in LangGraph agents.

        Uses the canonical implementation's signature and docstring.

        Returns:
            langchain_core.tools.StructuredTool
        """
        from langchain_core.tools import StructuredTool  # pylint: disable=import-outside-toplevel # Reason: Avoid hard dependency at module load

        resolved_name = self._resolve_nexus_name()
        resolved_description = self.implementation.__doc__ or self.description

        return StructuredTool.from_function(
            coroutine=self.implementation,
            name=resolved_name,
            description=resolved_description,
        )

    def to_mcp_tool(self) -> Any:
        """
        Convert to a FastMCP FunctionTool for programmatic registration.

        Wraps the implementation with track_mcp_tool() for PostHog analytics.

        Returns:
            fastmcp.tools.tool.FunctionTool
        """
        from fastmcp.tools.tool import FunctionTool  # pylint: disable=import-outside-toplevel # Reason: Avoid hard dependency at module load
        from seer.mcp.tracking import track_mcp_tool  # pylint: disable=import-outside-toplevel # Reason: Avoid circular import

        tracking_name = self._resolve_mcp_tracking_name()
        resolved_name = self.resolve_mcp_name()

        # Apply the tracking decorator to the implementation
        tracked_fn = track_mcp_tool(tracking_name)(self.implementation)

        return FunctionTool.from_function(
            fn=tracked_fn,
            name=resolved_name,
            description=self.description,
        )


class UnifiedToolRegistry:
    """
    Registry that holds ToolDefinitions and generates surface-specific tools.

    Acts as the single source of truth: tools are registered once, then
    get_langgraph_tools() and register_mcp_tools() produce framework-specific
    wrappers from the same definitions.
    """

    def __init__(self) -> None:
        self._tools: Dict[str, ToolDefinition] = {}

    def register(self, tool_def: ToolDefinition) -> ToolDefinition:
        """
        Register a tool definition. Idempotent — re-registering the same name is a no-op.

        Args:
            tool_def: The ToolDefinition to register

        Returns:
            The registered ToolDefinition
        """
        if tool_def.name in self._tools:
            return self._tools[tool_def.name]
        self._tools[tool_def.name] = tool_def
        logger.debug("Registered unified tool: %s (surface=%s)", tool_def.name, tool_def.surface)
        return tool_def

    def get_langgraph_tools(self) -> List[Any]:
        """
        Get all tools registered for the NEXUS surface as LangGraph StructuredTools.

        Returns:
            List of StructuredTool instances
        """
        tools = []
        for tool_def in self._tools.values():
            if ToolSurface.NEXUS in tool_def.surface:
                tools.append(tool_def.to_langgraph_tool())
        return tools

    def register_mcp_tools(self, mcp_server: Any) -> None:
        """
        Register all MCP-surface tools on a FastMCP server instance.

        Uses mcp_server.add_tool() for programmatic registration (no decorator needed).

        Args:
            mcp_server: FastMCP server instance
        """
        for tool_def in self._tools.values():
            if ToolSurface.MCP in tool_def.surface:
                mcp_tool = tool_def.to_mcp_tool()
                mcp_server.add_tool(mcp_tool)
                logger.debug("Registered MCP tool: %s", tool_def.resolve_mcp_name())

    def get(self, name: str) -> Optional[ToolDefinition]:
        """Get a tool definition by canonical name."""
        return self._tools.get(name)

    @property
    def tool_count(self) -> int:
        """Number of registered tools."""
        return len(self._tools)

    def clear(self) -> None:
        """Clear all registered tools. Primarily for testing."""
        self._tools.clear()


# Module-level singleton
unified_registry = UnifiedToolRegistry()
