name: allow-only-dev-to-main

on:
  pull_request:
    branches:
      - main

jobs:
  allow-only-dev-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if source branch is not dev
        run: |
          if [ "${{ github.head_ref }}" != "dev" ]; then
            echo "Only PRs from 'dev' can be merged into 'main'."
            exit 1
          fi
