name: Deploy to AWS

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'src/**'
      - 'Dockerfile'
      - 'pyproject.toml'
      - 'uv.lock'
      - 'migrations/**'

  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        type: choice
        options:
          - dev
          - main

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: false

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  ECS_API_SERVICE: ${{ secrets.ECS_API_SERVICE }}
  ECS_WORKER_SERVICE: ${{ secrets.ECS_WORKER_SERVICE }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-24.04-arm
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ----------------------------------------------------------------
      # LOGIC STEP: Determine which environment we are deploying to
      # ----------------------------------------------------------------
      - name: Set Environment Specific Variables
        id: env-selector
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "Deploying to PRODUCTION"
            echo "ECS_CLUSTER=${{ secrets.ECS_CLUSTER_MAIN }}" >> $GITHUB_ENV
            echo "IMAGE_TAG=main" >> $GITHUB_ENV
            echo "DATABASE_URL=${{ secrets.DATABASE_URL_MAIN }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "Deploying to DEVELOPMENT"
            echo "ECS_CLUSTER=${{ secrets.ECS_CLUSTER_DEV }}" >> $GITHUB_ENV
            echo "IMAGE_TAG=dev" >> $GITHUB_ENV
            echo "DATABASE_URL=${{ secrets.DATABASE_URL_DEV }}" >> $GITHUB_ENV
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Python and uv
        uses: astral-sh/setup-uv@v3
        with:
          python-version: "3.12"
          enable-cache: true

      - name: Run database migrations
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}

        run: |
          uv sync --frozen
          echo "Running database migrations"
          echo "Migrations HEADS: $(uv run aerich heads)"
          uv run aerich upgrade

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build, tag, and push image to Amazon ECR
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Force ECS service deployment API Service
        run: |
          aws ecs update-service \
            --cluster ${{ env.ECS_CLUSTER }} \
            --service ${{ env.ECS_API_SERVICE }} \
            --force-new-deployment


      - name: Force ECS service deployment Worker Service
        run: |
          aws ecs update-service \
            --cluster ${{ env.ECS_CLUSTER }} \
            --service ${{ env.ECS_WORKER_SERVICE }} \
            --force-new-deployment
